# Generated by Django 3.0.5 on 2020-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
